SELECT DISTINCT USER.USER_ID, USER.NICKNAME,
CONCAT_WS(' ', USER.CITY, USER.STREET_ADDRESS1, USER.STREET_ADDRESS2) 전체주소,
CONCAT_WS('-', LEFT(USER.TLNO, 3), SUBSTRING(USER.TLNO, 4, 4), RIGHT(USER.TLNO, 4)) 전화번호
FROM USED_GOODS_BOARD BOARD
JOIN USED_GOODS_USER USER
ON BOARD.WRITER_ID = USER.USER_ID
WHERE USER.USER_ID IN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(*) >= 3)
ORDER BY USER_ID DESC